name: deepspeed easy
debug: false
workspace: Kevin
project: LLMBlog1
environment:
  environment_variables:
    - NCCL_DEBUG=INFO
    - HF_HOME=/nvmefs1/kevin.musgrave/hf_cache
resources:
  slots_per_trial: 2
  resource_pool: A100
searcher:
  name: single
  max_length:
    batches: 5000
  metric: eval_accuracy
  smaller_is_better: false
hyperparameters:
  model: "mistralai/Mistral-7B-Instruct-v0.2"
  dataset_subset: "easy"
  training_args:
    output_dir: "/tmp/llm_finetuning"
    max_steps: 5000
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 4
    fp16: true
    evaluation_strategy: "steps"
    eval_steps: 1000
    logging_strategy: "steps"
    logging_steps: 100
    save_strategy: "steps"
    save_steps: 1000
    learning_rate: 1e-5
    deepspeed: "ds_configs/ds_config_stage_3.json"
entrypoint: >-
  python -m determined.launch.deepspeed
  python finetune.py
max_restarts: 0
# bind_mounts:
#   - container_path: /nvmefs1/agnieszka.ciborowska
#     host_path: /nvmefs1/agnieszka.ciborowska
#     propagation: rprivate
#     read_only: false